In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
url = 'https://data.cityofnewyork.us/api/views/6fi9-q3ta/rows.csv?accessType=DOWNLOAD'
df = pd.read_csv(url)
print(df.head())

           hour_beginning         location  Pedestrians  Towards Manhattan  \
0  04/30/2019 12:00:00 AM  Brooklyn Bridge            3                  3
1  12/31/2019 10:00:00 PM  Brooklyn Bridge           10                  9
2  12/31/2019 11:00:00 PM  Brooklyn Bridge            2                  0
3  12/31/2019 09:00:00 PM  Brooklyn Bridge           12                  0
4  04/01/2019 03:00:00 AM  Brooklyn Bridge            1                  0

   Towards Brooklyn weather_summary  temperature  precipitation        lat  \
0                 0             NaN          NaN            NaN  40.708164
1                 1          cloudy         42.0         0.0005  40.708164
2                 2          cloudy         42.0         0.0004  40.708164
3                12          cloudy         42.0         0.0036  40.708164
4                 1     clear-night         36.0         0.0000  40.708164

        long events                              Location1
0 -73.999509    NaN  (40.7081639691088, -73.9995087014816)
1 -73.999509    NaN  (40.7081639691088, -73.9995087014816)
2 -73.999509    NaN  (40.7081639691088, -73.9995087014816)
3 -73.999509    NaN  (40.7081639691088, -73.9995087014816)
4 -73.999509    NaN  (40.7081639691088, -73.9995087014816)

In [5]:
df['hour_beginning'] = pd.to_datetime(df['hour_beginning'])
df.info()
df['hour_beginning'].head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16057 entries, 0 to 16056
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   hour_beginning     16057 non-null  datetime64[ns]
 1   location           16057 non-null  object
 2   Pedestrians        16057 non-null  int64
 3   Towards Manhattan  16057 non-null  int64
 4   Towards Brooklyn   16057 non-null  int64
 5   weather_summary    16041 non-null  object
 6   temperature        16041 non-null  float64
 7   precipitation      16041 non-null  float64
 8   lat                16057 non-null  float64
 9   long               16057 non-null  float64
 10  events             1124 non-null   object
 11  Location1          16057 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(3), object(4)
memory usage: 1.5+ MB

0   2019-04-30 00:00:00
1   2019-12-31 22:00:00
2   2019-12-31 23:00:00
3   2019-12-31 21:00:00
4   2019-04-01 03:00:00
Name: hour_beginning, dtype: datetime64[ns]

1)Filter the data to include only weekdays (Monday to Friday) and plot a line graph showing the pedestrian counts for each day of the week.

In [6]:
df['day_name'] = df['hour_beginning'].dt.day_name()
df.head()

,hour_beginning,location,Pedestrians,Towards Manhattan,Towards Brooklyn,weather_summary,temperature,precipitation,lat,long,events,Location1,day_name
0,2019-04-30 00:00:00,Brooklyn Bridge,3,3,0,NaN,NaN,NaN,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Tuesday
1,2019-12-31 22:00:00,Brooklyn Bridge,10,9,1,cloudy,42.0,0.0005,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Tuesday
2,2019-12-31 23:00:00,Brooklyn Bridge,2,0,2,cloudy,42.0,0.0004,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Tuesday
3,2019-12-31 21:00:00,Brooklyn Bridge,12,0,12,cloudy,42.0,0.0036,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Tuesday
4,2019-04-01 03:00:00,Brooklyn Bridge,1,0,1,clear-night,36.0,0.0000,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Monday

In [7]:
weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
df_weekdays = df[df['day_name'].isin(weekdays)]

In [8]:
df_weekdays

,hour_beginning,location,Pedestrians,Towards Manhattan,Towards Brooklyn,weather_summary,temperature,precipitation,lat,long,events,Location1,day_name
0,2019-04-30 00:00:00,Brooklyn Bridge,3,3,0,NaN,NaN,NaN,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Tuesday
1,2019-12-31 22:00:00,Brooklyn Bridge,10,9,1,cloudy,42.0,0.0005,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Tuesday
2,2019-12-31 23:00:00,Brooklyn Bridge,2,0,2,cloudy,42.0,0.0004,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Tuesday
3,2019-12-31 21:00:00,Brooklyn Bridge,12,0,12,cloudy,42.0,0.0036,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Tuesday
4,2019-04-01 03:00:00,Brooklyn Bridge,1,0,1,clear-night,36.0,0.0000,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16051,2018-07-12 00:00:00,Brooklyn Bridge,77,39,38,partly-cloudy-night,72.0,0.0000,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Thursday
16052,2018-06-22 04:00:00,Brooklyn Bridge,7,4,3,partly-cloudy-night,67.0,0.0000,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Friday
16053,2018-07-19 06:00:00,Brooklyn Bridge,192,89,103,clear-day,65.0,0.0000,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Thursday
16055,2018-07-24 18:00:00,Brooklyn Bridge,2016,1069,947,partly-cloudy-day,80.0,0.0000,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Tuesday
16056,2018-07-23 00:00:00,Brooklyn Bridge,57,20,37,cloudy,75.0,0.0103,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Monday

In [11]:
weekday_counts = df_weekdays.groupby('day_name')['Pedestrians'].sum().reindex(weekdays)
weekday_counts

day_name
Monday       1481435
Tuesday      1394963
Wednesday    1310900
Thursday     1370880
Friday       1588068
Name: Pedestrians, dtype: int64

In [ ]:
plt.figure(figsize=(12, 6))
weekday_counts.plot(kind='line', marker='o')
plt.title('Pedestrian Counts by Weekday')
plt.xlabel('Day of the Week')
plt.ylabel('Total Pedestrian Counts')
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

2) Track pedestrian counts on the Brooklyn Bridge for the year 2019 and analyze how different weather conditions influence pedestrian activity in that year. Sort the pedestrian count data by weather summary to identify any correlations( with a correlation matrix) between weather patterns and pedestrian counts for the selected year.

In [14]:
df_2019 = df[df['hour_beginning'].dt.year == 2019]
df_2019

,hour_beginning,location,Pedestrians,Towards Manhattan,Towards Brooklyn,weather_summary,temperature,precipitation,lat,long,events,Location1,day_name
0,2019-04-30 00:00:00,Brooklyn Bridge,3,3,0,NaN,NaN,NaN,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Tuesday
1,2019-12-31 22:00:00,Brooklyn Bridge,10,9,1,cloudy,42.0,0.0005,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Tuesday
2,2019-12-31 23:00:00,Brooklyn Bridge,2,0,2,cloudy,42.0,0.0004,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Tuesday
3,2019-12-31 21:00:00,Brooklyn Bridge,12,0,12,cloudy,42.0,0.0036,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Tuesday
4,2019-04-01 03:00:00,Brooklyn Bridge,1,0,1,clear-night,36.0,0.0000,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8756,2019-02-10 12:00:00,Brooklyn Bridge,1388,623,765,clear-day,31.0,0.0000,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Sunday
8757,2019-11-10 08:00:00,Brooklyn Bridge,305,168,137,partly-cloudy-day,39.0,0.0000,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Sunday
8758,2019-11-07 01:00:00,Brooklyn Bridge,0,0,0,clear-night,43.0,0.0000,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Thursday
8759,2019-04-26 11:00:00,Brooklyn Bridge,1437,613,824,cloudy,55.0,0.0000,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Friday
8760,2019-09-10 19:00:00,Brooklyn Bridge,981,476,505,partly-cloudy-day,72.0,0.0000,40.708164,-73.999509,NaN,"(40.7081639691088, -73.9995087014816)",Tuesday

In [15]:
weather_grouped = df_2019.groupby('weather_summary')['Pedestrians'].sum().reset_index()

In [16]:
weather_encoded = pd.get_dummies(df_2019['weather_summary'])
weather_encoded['Pedestrians'] = df_2019['Pedestrians']

In [17]:
correlation_matrix = weather_encoded.corr()
pedestrian_correlation = correlation_matrix['Pedestrians'].sort_values(ascending=False)
print(pedestrian_correlation)

Pedestrians            1.000000
partly-cloudy-day      0.497867
clear-day              0.339758
wind                  -0.000170
sleet                 -0.017091
fog                   -0.026457
snow                  -0.034052
cloudy                -0.081255
rain                  -0.138581
partly-cloudy-night   -0.282081
clear-night           -0.377297
Name: Pedestrians, dtype: float64

3) Implement a custom function to categorize time of day into morning, afternoon, evening, and night, and create a new column in the DataFrame to store these categories. Use this new column to analyze pedestrian activity patterns throughout the day.

In [18]:
def categorize_time_of_day(hour):
    if 5 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 21:
        return 'Evening'
    else:
        return 'Night'

In [20]:
df['time_of_day'] = df['hour_beginning'].dt.hour.apply(categorize_time_of_day)
time_of_day_activity = df.groupby('time_of_day')['Pedestrians'].mean()
print(time_of_day_activity)

time_of_day
Afternoon    1749.484305
Evening       908.873318
Morning       529.699338
Night          50.086680
Name: Pedestrians, dtype: float64